spring:
#  profiles:
#    active: native  配置本地配置文件位置 默認src/main/resource目录下检索
  application:
    name: conig-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MeddKim/spring-cloud-demo
          search-paths: config-repo
          username: meddkim
          password: wzy19920323
#        native:
#          search-locations: file:F:/properties 使用本地文件位置

server:
  port: 8881

