server:
  port: 8201

eureka:
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8111/eureka/,http://peer2:8112/eureka/
spring:
  application:
    name: compute-service