server:
  port: 8201
spring:
  application:
    name: compute-service
eureka:
  client:
    serviceUrl:
#      defaultZone: http://peer1:8111/eureka/,http://peer2:8112/eureka/
      defaultZone: http://peer1:8111/eureka/


# 以下配置了随机port随机eureka.instance.instance-id但是这样配置导致ribbon无法在通过compute-service访问
# 空下来需要了解这个问题发生的原因

#server:
#  port: ${random.int[8201,8205]} # 设置port:0也会随机分配
#spring:
#  application:
#    name: compute-service
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8111/eureka/,http://peer2:8112/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${random.int}